# Generated by Django 5.1.2 on 2026-03-09 16:39

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Word",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("english_word", models.CharField(max_length=128, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=150, unique=True)),
                ("transcription", models.CharField(max_length=128)),
                ("ukrainian_translation", models.CharField(max_length=256)),
                ("context_sentence", models.TextField()),
                ("origin", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["english_word"],
            },
        ),
    ]
