# Generated by Django 5.1.2 on 2026-05-18 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dictionary", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TranslationOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=256)),
                (
                    "part_of_speech",
                    models.CharField(
                        choices=[
                            ("noun", "Noun"),
                            ("verb", "Verb"),
                            ("adjective", "Adjective"),
                            ("adverb", "Adverb"),
                            ("pronoun", "Pronoun"),
                            ("preposition", "Preposition"),
                            ("conjunction", "Conjunction"),
                            ("interjection", "Interjection"),
                            ("phrase", "Phrase"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("priority", models.PositiveSmallIntegerField(default=1)),
                ("usage_note", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "ordering": ["priority", "id"],
            },
        ),
        migrations.AddField(
            model_name="word",
            name="source_language",
            field=models.CharField(
                choices=[("en", "English"), ("uk", "Ukrainian")],
                default="en",
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="word",
            name="target_language",
            field=models.CharField(
                choices=[("en", "English"), ("uk", "Ukrainian")],
                default="uk",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="word",
            name="english_word",
            field=models.CharField(max_length=128),
        ),
        migrations.AddConstraint(
            model_name="word",
            constraint=models.UniqueConstraint(
                fields=("english_word", "source_language", "target_language"),
                name="unique_word_with_direction",
            ),
        ),
        migrations.AddField(
            model_name="translationoption",
            name="word",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="translation_options",
                to="dictionary.word",
            ),
        ),
        migrations.AddConstraint(
            model_name="translationoption",
            constraint=models.UniqueConstraint(
                fields=("word", "text", "part_of_speech"),
                name="unique_translation_option_per_word",
            ),
        ),
    ]
